import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import {cn} from "@/lib/utils";
import "react-loading-skeleton/dist/skeleton.css";
import {ReduxProvider} from "@/redux/provider";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html className="min-h-screen" lang="en">
      <body className={cn("font-sans antialiased grainy", inter.className)}>
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}
